version: '3.8'

services:
  frontend:
    image: muhammadsawalha/frontend-service:${FRONTEND_IMAGE_TAG:-0.0.1}
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - agent
    networks:
      - polyai-net

  agent:
    image: muhammadsawalha/agent-service:${AGENT_IMAGE_TAG:-0.0.1}
    container_name: agent
    ports:
      - "8000:8000"
    environment:
      - YOLO_SERVICE_URL=http://yolo:8080
      - IMG_PROC_MCP_URL=http://img-proc-mcp:9000/mcp
      - MODEL_PROVIDER=bedrock_converse
      - MODEL=amazon.nova-lite-v1:0
      - AWS_REGION=us-east-1
    volumes:
      - ~/.aws:/root/.aws:ro
    depends_on:
      - yolo
      - img-proc-mcp
    networks:
      - polyai-net

  yolo:
    image: muhammadsawalha/yolo-service:${YOLO_IMAGE_TAG:-0.0.1}
    container_name: yolo
    ports:
      - "8080:8080"
    networks:
      - polyai-net

  img-proc-mcp:
    image: muhammadsawalha/img-proc-mcp-service:${IMG_PROC_MCP_IMAGE_TAG:-0.0.1}
    container_name: img-proc-mcp
    ports:
      - "9000:9000"
    environment:
      - AWS_REGION=us-east-1
    volumes:
      - ~/.aws:/root/.aws:ro
    networks:
      - polyai-net

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    pid: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"
    networks:
      - polyai-net
      - monitoring-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    depends_on:
      - yolo
      - node-exporter
    networks:
      - monitoring-net
      - polyai-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - monitoring-net

volumes:
  prometheus_data:
  grafana_data:

networks:
  polyai-net:
    driver: bridge
  monitoring-net:
    driver: bridge