apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual-dev
  resources:
    requests:
      storage: 5Gi
